# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bill Dean - Front-End Web Developer
email: 742designs@gmail.com
description: Hello World! My name is Bill Dean and I'm a web developer based in Toronto, Canada. I specialize in HTML5, CSS3, JavaScript, and WordPress.
og-description: My name is Bill Dean and I'm a web developer based in Toronto, Canada.
og-image: https://bill742.github.io/images/hero.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bill742.github.io" # the base hostname & protocol for your site
twitter_username: bil742
github_username:  bill742
codepen_username:  bill742
linkedin_username:  bill742

# Build settings
markdown: kramdown
future: true
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - octopress-autoprefixer
